### ISSUE TITLE
Double bookings show as available room

### ISSUE THREAD

**Issue by Merei1** [flora-gr/gorlaeus_bookings#15]
When a room is double booked, e.g. 2 groups or courses together in 1 room, the app doesn't pick this up and shows a green room. I noticed yhis for  Oct 31st when room C2 and C3 are both double booked for the afternoon but they appear to be available... Not 100% sure the double bookings are the cause, so please check for other possible causes.

**Comment by flora-gr** [comment]
Great find! I was not aware of the possibility of double bookings. The error has been found and I will fix it today, so you can expect an update in your Play Store sometime in the coming days.
