### ISSUE TITLE
LMUY 04.28 not available for booking

### ISSUE THREAD

**Issue by burgerga** [flora-gr/gorlaeus_bookings#17]
Thanks for creating this app, very nice! 

I tried to book LMUY 04.28 and got the following response from the service desk:

> It’s not possible to book room LMUY 04.28, this room is not ours anymore but from LIACS.

**Comment by flora-gr** [comment]
Hi, thanks for bringing this to my attention! @vanhasseltlab just confirmed that this room will not be available for booking any more. I will remove it from the room options in the coming app update.
